import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { MATERIAL_ICONS } from './materialIcons.generated';
import { MATERIAL_ICON_NAMES } from './LanguageIcon';

const generatedSource = readFileSync(resolve(__dirname, 'materialIcons.generated.ts'), 'utf8');

describe('material icon subset', () => {
  it('includes every icon the language badges reference', () => {
    for (const name of MATERIAL_ICON_NAMES) {
      expect(MATERIAL_ICONS[name], `missing material icon "${name}" — run npm run generate:icons`).toBeDefined();
    }
  });

  it('contains no icon the language badges do not reference', () => {
    for (const name of Object.keys(MATERIAL_ICONS)) {
      expect(MATERIAL_ICON_NAMES).toContain(name);
    }
  });

  it('extracts well-formed icons', () => {
    for (const [name, icon] of Object.entries(MATERIAL_ICONS)) {
      expect(icon.body.length, `${name} has an empty body`).toBeGreaterThan(0);
      expect(icon.width, `${name} width`).toBeGreaterThan(0);
      expect(icon.height, `${name} height`).toBeGreaterThan(0);
    }
  });

  it('keeps the generated file untouched by hand edits', () => {
    expect(generatedSource.startsWith('// AUTO-GENERATED by scripts/generate-material-icons.mjs')).toBe(true);
  });
});
