import type { LiveArtifactsPromptMode, VisionPromptMode } from '@/types';
import type { SupportedLanguage } from '@/i18n/languageRegistry';
import {
  BBOX_PROMPT_MARKER,
  HD_GUIDE_PROMPT_MARKER,
  LIVE_ARTIFACTS_PROMPT_MARKERS,
  loadBboxSystemPrompt,
  loadDeepSearchSystemPrompt,
  loadHdGuideSystemPrompt,
  loadLiveArtifactsSystemPrompt,
  loadLocalPythonSystemPrompt,
} from './promptRegistry';

export interface PromptCompositorContext {
  /** User-defined persona or instruction (clean, un-augmented). */
  userInstruction?: string | null;

  /** Feature mode protocols */
  isLiveArtifactsEnabled?: boolean;
  liveArtifactsPromptMode?: LiveArtifactsPromptMode;
  customLiveArtifactsPrompt?: string | null;
  visionPromptMode?: VisionPromptMode;

  /** Tool call behavior directives */
  isDeepSearchEnabled?: boolean;
  isLocalPythonEnabled?: boolean;
  isGemmaModel?: boolean;

  /** Media navigation locate directives */
  locateDirectives?: string[];

  /** Language for localized prompts */
  language?: SupportedLanguage;
}

/**
 * Strips legacy feature markers from instruction while preserving any preceding user instruction text.
 * If the instruction was entirely generated by old versions that embedded the full protocol into
 * systemInstruction, returns empty string.
 */
export const stripLegacyFeatureMarkers = (instruction?: string | null): string => {
  if (!instruction) return '';
  const trimmed = instruction.trim();

  const allMarkers = [...LIVE_ARTIFACTS_PROMPT_MARKERS, BBOX_PROMPT_MARKER, HD_GUIDE_PROMPT_MARKER];

  let earliestIndex = -1;
  for (const marker of allMarkers) {
    const idx = trimmed.indexOf(marker);
    if (idx !== -1) {
      if (earliestIndex === -1 || idx < earliestIndex) {
        earliestIndex = idx;
      }
    }
  }

  if (earliestIndex === -1) {
    return trimmed;
  }

  if (earliestIndex === 0) {
    return '';
  }

  return trimmed.slice(0, earliestIndex).trim();
};

/**
 * Composes a multi-layered system instruction string for model generation.
 *
 * Layer 1: User-defined instruction (custom persona / scenario)
 * Layer 2: Feature protocols (Live Artifacts, BBox, HD Guide)
 * Layer 3: Tool directives (Deep Search, Local Python)
 * Layer 4: Media locate directives (PDF pages, video timestamps)
 */
export const composeSystemInstruction = async (context: PromptCompositorContext): Promise<string | undefined> => {
  const segments: string[] = [];

  // Layer 1: User-defined instruction
  const cleanUserInstruction = stripLegacyFeatureMarkers(context.userInstruction);
  if (cleanUserInstruction) {
    segments.push(cleanUserInstruction);
  }

  // Layer 2: Feature protocols
  // If media locate directives are active, omit Live Artifacts to avoid conflicting markers.
  const hasLocateDirectives = (context.locateDirectives?.length ?? 0) > 0;
  if (context.isLiveArtifactsEnabled && !hasLocateDirectives) {
    const customPrompt = context.customLiveArtifactsPrompt?.trim();
    if (customPrompt) {
      segments.push(customPrompt);
    } else {
      const laPrompt = await loadLiveArtifactsSystemPrompt(
        context.language ?? 'zh',
        context.liveArtifactsPromptMode ?? 'inline',
      );
      if (laPrompt?.trim()) {
        segments.push(laPrompt.trim());
      }
    }
  }

  if (context.visionPromptMode === 'bbox') {
    const bboxPrompt = await loadBboxSystemPrompt();
    if (bboxPrompt?.trim()) {
      segments.push(bboxPrompt.trim());
    }
  } else if (context.visionPromptMode === 'hdGuide') {
    const hdGuidePrompt = await loadHdGuideSystemPrompt();
    if (hdGuidePrompt?.trim()) {
      segments.push(hdGuidePrompt.trim());
    }
  }

  // Layer 3: Tool directives
  if (context.isDeepSearchEnabled && !context.isGemmaModel) {
    const deepSearchPrompt = await loadDeepSearchSystemPrompt();
    if (deepSearchPrompt?.trim()) {
      segments.push(deepSearchPrompt.trim());
    }
  }

  if (context.isLocalPythonEnabled) {
    const localPythonPrompt = await loadLocalPythonSystemPrompt();
    if (localPythonPrompt?.trim()) {
      segments.push(localPythonPrompt.trim());
    }
  }

  // Layer 4: Media locate directives
  if (hasLocateDirectives) {
    const locateText = context.locateDirectives!.filter(Boolean).join('\n\n');
    if (locateText) {
      segments.push(locateText);
    }
  }

  return segments.length > 0 ? segments.join('\n\n') : undefined;
};
